### ISSUE TITLE
Thanks for your prompt response. But it doesn't work. I am not sure if my setting is correct.

### ISSUE THREAD

**Issue by terrychenzw** [scottwillmoore/obsidian-short-links#11]
Thanks for your prompt response. But it doesn't work. I am not sure if my setting is correct.
![short link issue](https://github.com/scottwillmoore/obsidian-short-links/assets/114856910/4531d979-02c7-4acc-969d-0c5047ac906b)

_Originally posted by @terrychenzw in https://github.com/scottwillmoore/obsidian-short-links/issues/9#issuecomment-1603627479_

**Comment by scottwillmoore** [comment]
Duplicate #9.
