### ISSUE TITLE
New version (1.1.3) doesn't work in Reading mode.

### ISSUE THREAD

**Issue by xelaras** [scottwillmoore/obsidian-short-links#13]
**Obsidian Version: 1.4.2**

Version 1.1.2 of Obsidian Short Links works fine in Reading mode:

<img width="353" alt="Immagine 2023-08-09 084203" src="https://github.com/scottwillmoore/obsidian-short-links/assets/80386815/c48b6048-f95b-43b3-a53f-c1e6cf3f13e6">

But it doesn't in version 1.1.3 of the plugin:

<img width="409" alt="Immagine 2023-08-09 085635" src="https://github.com/scottwillmoore/obsidian-short-links/assets/80386815/c4a84d76-81bb-4e0f-9bcf-f62f6b6921cd">

**Comment by scottwillmoore** [comment]
Weird, is Obsidian 1.4.2 a pre-released version? I can only see 1.3.7 as the [latest version that is released](https://github.com/obsidianmd/obsidian-releases/releases).

Anyway, I think this issue should be fixed now. I reverted the changes made in 1.1.3.

**Comment by xelaras** [comment]
Yes, Obsidian 1.4.2 is an insider build version (you need the Catalyst license to access it).
