### ISSUE TITLE
Short links to files does not work when heading is included

### ISSUE THREAD

**Issue by xiaonanz** [scottwillmoore/obsidian-short-links#6]
Hi Scott, 

Thank you for making this plugin, it was delightful to come across it. It solved one of my pet peeves with how obsidian links are displayed. 

I use the plugin with "Short links to files" enabled and all other options disabled. However, I found that under this setting, `[[path/to/file#heading]]` would render as `path/to/file#heading` in live preview and `path/to/file > heading` in reading mode. I think the correct behavior should be rendering them as `file#heading` in live preview and `file > heading` in reading mode. 

ps: obsidian displays `#heading` differently in live preview (`#heading`) vs in reading mode (`> heading`), if you could fix the live preview rendering to be the same as in reading mode in this plugin, that would be even more wonderful. 

Thanks for your plugin again, appreciate if you can address this issue, 

Xiaonan

**Comment by scottwillmoore** [comment]
I think this is fixed, please let me know if there are any other edge cases I missed!
